### PR TITLE
feat: implement "autoWebviewName" option

### PR DESCRIPTION
**Pull request by DudaGod**
Fix problem described here - https://github.com/appium/appium/issues/17639

### CODE REVIEW

**Review by mykola-mokhnach — APPROVED** [review]
Please do not forget to document the new capability in UIA2 driver's readme later

**Comment by DudaGod** [comment]
> Please do not forget to document the new capability in UIA2 driver's readme later

https://github.com/appium/appium-uiautomator2-driver/pull/558

**Comment by mykola-mokhnach** [comment]
Could you please rebase the PR with master? I've updated the unit tests there

**Comment by KazuCocoa** [comment]
fyi: Updated via the web ui

**Comment by DudaGod** [comment]
> Could you please rebase the PR with master? I've updated the unit tests there

Done

> fyi: Updated via the web ui

I prefer through cli

**Pull request merged**
