### PR TITLE
add initial chrome browser support

### PR DESCRIPTION
**Pull request by jlipps**
@Jonahss @moizjv here's the initial work. I got a chrome session started, yay! I think there's still some kinks to be worked out, particularly around how we want to handle contexts in chrome sessions (to be honest I'm not sure this works at all in current appium).

but anyway ready for review and for someone to take over!

### CODE REVIEW

**Comment by jlipps** [comment]
ok I actually fixed up the way contexts are handled so we're using the same paradigm for both chrome and hybrid. i got a working chrome session yay!

**Comment by Jonahss** [comment]
looks good on first pass. I'll merge and testy test some stuff.

**Comment by moizjv** [comment]
:+1:

**Comment by jlipps** [comment]
@Jonahss sounds good let me know when testy testing is done

**Comment by jlipps** [comment]
@Jonahss rebased off your merge

**Comment by jlipps** [comment]
still awaiting some @Jonahss love

**Comment by jlipps** [comment]
k tested with Chrome and Browser and it's working. going to merge

**Pull request merged**
