### PR TITLE
Skip setting of mock location app for emulator

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This is a copy of https://github.com/appium/appium-android-driver/pull/239, which has been accidentally deleted before it was merged.

Addresses https://github.com/appium/appium/issues/9000

### CODE REVIEW

**Comment by AnastasiiaKravets** [comment]
**Unable to create session on emulator with API>=24**

This fix doesn't help.
The problem from https://github.com/appium/appium/issues/9000 is the same.


org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command.
Original error: Error executing adbExec.
Original error: 'Command 'C:\Users\xxx\android-sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell appops set io.appium.settings android:mock_location allow' exited with code 4294967295';
Stderr: 'Error: No UID for io.appium.settings in user 0'; Code: '4294967295' (WARNING: The server did not provide any stacktrace information)

**Environment**
Appium version (or git revision) that exhibits the issue: v1.6.6-beta.4
Desktop OS/version used to run Appium: Win
Node.js version (unless using Appium.app|exe): v8.2.1
Mobile platform/version under test: Android API>=24
Real device or emulator/simulator: Emulator
Appium CLI or Appium.app|exe: CLI

**Comment by jlipps** [comment]
@AnastasiiaKravets were you running this repo from source? It's very possible that this fix has not yet been published.

**Comment by AnastasiiaKravets** [comment]
@jlipps I run it from https://github.com/appium/appium/releases

**Comment by jlipps** [comment]
@AnastasiiaKravets then you will have to wait until the next release in order to test this.

**Pull request merged**
