### PR TITLE
Added instrumentation tests commands

### PR DESCRIPTION
**Pull request by dmitryfisko**
I am want to use Appium as infrastructure for running instrumentation tests on multiple devices or emulators by Selenium Grid. This new approach require new routes.

For running instrumentation test in apk
instrumentationClassTest(testClass, packageName)

For running all instrumentation tests in apk
instrumentationPackageTest(packageName)

For installing apk without activity (apk with test)
instrumentationInstallTest(apkPath)

### CODE REVIEW

**Comment by imurchie** [comment]
Your git configured email appears to point to my email? I'm not sure what is going on here.

**Comment by dmitryfisko** [comment]
How does fix that? Commit title "imurchie committed with dmitryfisko"

**Comment by dmitryfisko** [comment]
Not ready yet

**Comment by imurchie** [comment]
I'm not entirely sure. I think you need to make sure your email in git config is yours.

**Pull request closed without merging**
