### PR TITLE
Seperated SwipeOpts and SwipeActionCall to extend swipeOpts to uiautomator2

### PR DESCRIPTION
**Pull request by anandsadu**
Changes in this PR are with respective to the changes [here.](https://github.com/appium/appium-uiautomator2-driver/pull/29) Removed redundant code in appium-uiautomator2-driver

### CODE REVIEW

**Comment by imurchie** [comment]
Sorry, I missed this. Is it still needed for the UIAutomator 2 driver?

**Comment by anandsadu** [comment]
Yes ..it is required. Changes  are with respective to [PR](https://github.com/appium/appium-uiautomator2-driver/pull/29)

**Comment by imurchie** [comment]
Alright. Sorry for the delay. But it looks good to me.

**Comment by imurchie** [comment]
Published as `appium-android-driver@1.10.24`.

**Pull request merged**
