### PR TITLE
flexible appPackage, autoWebview logic, Context fix

### PR DESCRIPTION
**Pull request by scottdixon**
- appPackage: Backward compatibility - our docs don't suggest that we support this feature but we do in current Appium and our existing e2e tests rely on it.

- autoWebview logic

- context fix: with the additional autoWebview logic, some tests were failing from context related issues, moving the `curContext` to createSession() resolves the issues.

### CODE REVIEW

**Comment by imurchie** [comment]
Does this supercede #66?

**Comment by scottdixon** [comment]
yep

**Comment by imurchie** [comment]
Cool.

Still looks like the e2e test is failing. https://github.com/appium/appium-android-driver/blob/master/test/functional/driver-e2e-specs.js#L60 needs updating.

**Comment by scottdixon** [comment]
Please don't merge this yet.

**Comment by scottdixon** [comment]
cc) @jlipps

**Comment by jlipps** [comment]
LGTM!

**Pull request merged**
