### PR TITLE
Update appium-adb, include gulp as a dev dependency.

### PR DESCRIPTION
**Pull request by fuzzybinary**

### CODE REVIEW

**Comment by jlipps** [comment]
@fuzzybinary i see that we are bumping the major version of appium-adb. are there any breaking changes we have to account for in its usage in this package?

**Comment by mykola-mokhnach** [comment]
I'd rather wait until https://github.com/appium/appium-android-driver/pull/287 is merged

**Comment by mykola-mokhnach** [comment]
@KazuCocoa ping

**Comment by KazuCocoa** [comment]
> are there any breaking changes we have to account for in its usage in this package?

Yes, my changing #287 related to `appium-adb` 5.0.0 which locale related method.
Hopefully, I'd love this PR wait until my PR finished.(I think I can finish soon.) Or I'd love to include this changes in my PR since I'll update `appium-adb` to 5.2.0(to include https://github.com/appium/appium-adb/pull/279 )

**Comment by jlipps** [comment]
great let's hold off and wait for @KazuCocoa then

**Comment by KazuCocoa** [comment]
included in https://github.com/appium/appium-android-driver/pull/287

**Pull request closed without merging**
