### PR TITLE
use appium-base-driver instead of mjsonwp and express

### PR DESCRIPTION
**Pull request by jlipps**

### CODE REVIEW

**Comment by jlipps** [comment]
PR to make sure build passes

**Comment by jlipps** [comment]
```
> gulp once
[19:49:48] Using gulpfile ~/build/appium/appium-android-driver/gulpfile.js
[19:49:48] Starting 'once'...
[19:49:48] Starting 'clean'...
[19:49:48] Finished 'clean' after 41 ms
[19:49:48] Starting 'jshint'...
[19:49:49] Finished 'jshint' after 1.51 s
[19:49:49] Starting 'lint'...
[19:49:49] Finished 'lint' after 16 μs
[19:49:49] Starting 'transpile'...
[19:50:00] Finished 'transpile' after 10 s
[19:50:00] Starting 'unit-test'...
[19:50:02] Error in plugin 'gulp-mocha'
Message:
    Cannot find module 'request-promise'
Details:
    code: MODULE_NOT_FOUND
```

This is odd.... unsure what is trying to depend on this

**Comment by jlipps** [comment]
ooooohhh right basedriver exports tests which android-driver runs, but basedriver only has request-promise in devDeps. it is actually a real dep in that case. updating.

**Comment by jlipps** [comment]
pushed again because of the baseServer bug

**Comment by jlipps** [comment]
ok travis is fixed. @imurchie do we know if cloudbees android tests are running at the moment?

**Comment by imurchie** [comment]
Yeah. The tests are running but it never reports back about the status. I looked at it but it was nothing obvious and I didn't have the time to debug properly.

https://team-appium.ci.cloudbees.com/job/Appium-android-driver/ (there is a flakey test that is on my radar, so if a build fails, check).

**Comment by jlipps** [comment]
```
  1) Localization - locale @skip-ci @skip-real-device should start as US:
     Error: Error occured while starting App. Original error: io.appium.android.apis/io.appium.android.apis.ApiDemos never started
      at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
      at ADB.callee$0$0$ (lib/tools/apk-utils.js:80:9)
      at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:67:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:315:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at GeneratorFunctionPrototype.invoke (node_modules/babel-runtime/regenerator/runtime.js:136:37)
      at bound (domain.js:287:14)
      at GeneratorFunctionPrototype.runBound (domain.js:300:12)
      at run (node_modules/core-js/library/modules/es6.promise.js:104:47)
      at node_modules/core-js/library/modules/es6.promise.js:115:28
      at flush (node_modules/core-js/library/modules/$.microtask.js:19:5)
```

is this the flake? it has `@skip-ci ` so not sure why it's even running...

just confirm then i'll go ahead and merge

**Comment by imurchie** [comment]
It is a flake, yes. We are using the `gulp e2e-test` task, which, as far as I can tell, does not respect `@skip-ci`.

**Comment by jlipps** [comment]
published as 1.10.5

**Pull request merged**
