### PR TITLE
1.5 cleanup - Todos, style

### PR DESCRIPTION
**Pull request by scottdixon**
- Style cleanup.
- Commands: get/set/accept/dismiss alert.
- Resolved TODO: validate capabilities (app, app package, browser).
- Resolved TODO: document recreateChromeDriverSessions.
- Resolved TODO: throw an error if appPackage isn't found on device.
- Additional tests.

### CODE REVIEW

**Comment by scottdixon** [comment]
@jlipps @moizjv @imurchie

**Comment by jlipps** [comment]
LGTM!

**Comment by imurchie** [comment]
Me too!

**Comment by scottdixon** [comment]
Made one change:
`!helpers.isChromeBrowser(caps.browserName.toLowerCase())` -> `!helpers.isChromeBrowser(caps.browserName)`

**Comment by jlipps** [comment]
LGTM, feel free to merge when ready

**Pull request merged**
