### PR TITLE
Refactored Drag, Swipe & Keys

### PR DESCRIPTION
**Pull request by sravanmedarapu**
- Refactored Drag, Swipe and Keys

### CODE REVIEW

**Comment by imurchie** [comment]
Looks good to me. Is this ready to merge on your end, @sravanmedarapu ?

**Comment by sravanmedarapu** [comment]
@imurchie, this PR ready to merge,  but I don't have rights to merge PRs.

**Comment by imurchie** [comment]
I more meant, are you adding more to it. I'll merge.

**Comment by sravanmedarapu** [comment]
Nothing else, Please merge.

**Comment by imurchie** [comment]
Merged. Published in `appium-android-driver@1.10.27`.

**Pull request merged**
