### PR TITLE
add apis for recording the screen

### PR DESCRIPTION
**Pull request by heeseon**
added two apis 
1. startRecordingScreen
2. stopRecordingScreen

### CODE REVIEW

**Comment by imurchie** [comment]
This has a lot of stuff that already exists in the codebase.

**Comment by heeseon** [comment]
then.. I can't apply it ? I resolved timing issue, please check the code, and unit test case.

**Comment by imurchie** [comment]
You need to remove all the performance stuff. That came in before. It looks like you worked off an old branch.

**Comment by heeseon** [comment]
removed all the performance stuff

**Comment by imurchie** [comment]
I do not understand why you've deleted a bunch of other stuff to put this in. Are you intending for there to be no methods for getting performance stats?

What more reasonably should happen is you should start a new branch, off of the latest master for the driver, and add a `lib/commands/recording.js` file with these methods, and then the associated tests.

**Pull request closed without merging**
