### PR TITLE
Capability to extract chromeAndroidPackagee from context_name

### PR DESCRIPTION
**Pull request by yaphatak**
This will allow us to to connect to multiple apps with webivew in same test session.

### CODE REVIEW

**Comment by imurchie** [comment]
What happens if this is always on? Does it affect the functioning of webviews?

Also, if this is a capability, it also needs to be added to https://github.com/appium/appium-android-driver/blob/master/lib/desired-caps.js

**Comment by jlipps** [comment]
So @yaphatak if I understand your change correctly, you want people to be able to do something like this:

```
driver.setContext("WEBVIEW_com.android.foo")
```

even if `com.android.foo` is not the currently running app?

**Comment by yaphatak** [comment]
That is correct. That's why this wont be default behavior. We can do same using `chromeAndroidProcess` but then you need to know `processid`

**Comment by imurchie** [comment]
Excellent! Thanks!

**Comment by imurchie** [comment]
Published in `appium-android-driver@1.11.0`

**Pull request merged**
