### PR TITLE
Allow way to pass chromeAndroidPackage

### PR DESCRIPTION
**Pull request by yaphatak**
This is useful when you are launching an app from another app.
Fixes https://github.com/appium/appium/issues/7194

### CODE REVIEW

**Comment by imurchie** [comment]
Looks good! Can you sign the CLA (again, unfortunately, but since joining the JS Foundation we have to use their system).

**Comment by yaphatak** [comment]
@imurchie I realized that. I am already following with our internal advisor on this.

Also, don't you think we should provide way to pass an `optional` parameter for `setContext` to pass `androidPackage` for `android` and `bundleId` for `ios`. Because today we can do multiple app testing in both `android` and `ios`

**Comment by imurchie** [comment]
That is probably a good idea. It's a method from the Selenium spec, so things would have to be changed there, though.

**Comment by yaphatak** [comment]
@imurchie Yes and that's why I added @jlipps in this conversation :)

**Comment by yaphatak** [comment]
@imurchie signed

**Comment by jlipps** [comment]
@yaphatak I'm a bit confused. when you get contexts, does the one you want not appear in the list?

**Comment by imurchie** [comment]
Published in `appium-android-driver@1.10.35`.

**Comment by yaphatak** [comment]
@jlipps I just saw this. I think its good to have `chromeAndroidProcess ` and it looks like it is already supported now. For `chromeAndroidProcess `  we still have to run some command to get coorect process. Today we get context names as `webview_pkgname`. So I am thinking extract pkg name from context anme

**Pull request merged**
